apiVersion: v1
kind: Secret
metadata:
  namespace: mobility-service-0
  name: ms1-secret-tls
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN0RENDQVp3Q0NRRHZyckZhRWxGMWp6QU5CZ2txaGtpRzl3MEJBUXNGQURBVk1STXdFUVlEVlFRREV3cHIKZFdKbGNtNWxkR1Z6TUI0WERUSXpNRFl5TVRJeU16SXlNRm9YRFRJME1EWXlNREl5TXpJeU1Gb3dJekVSTUE4RwpBMVVFQXd3SWJYTXRZV1J0YVc0eERqQU1CZ05WQkFvTUJXRmtiV2x1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBOVZKRHFNeW9HdU1PZXNLZ2RtTTV1NTUrYXp2ZG9DSWliSFF3NFp5MmF5K0sKNkhlVWRiZVhKVUhzV0gzZzFQNVZ3SHNaNlRwUkpMSm9UaERZWjJoazlMVXVYdFVYalZZbm1reXROS2grNi82egpqYTRUeWw0LzJHZk42KzFieWJOd3B4cXdNTjcxU2F5dTZCNHl5Mmt4eFVUcWFvcHE3VElqVjBCU3F3NTU3WWNVCldyQVpTZVZUZ0tkd2ZhOEJpOWk3S3VFRzF5Umw2KzhWc3R3eWpwU2NHZnNvWGtXNDlONjBvZnZ5bjZmMUlSM0wKT0pwK1Npa2ttNytZU2tyN1N1eEdPU0NWQUM2OG5WVHZOaXJrc1BlRGEzM1ZpNkJORVlTelB5VENuNnluZWh0NQpucWNDTFEzbGE0RVNSbjdCZzZHOHlpd2xEUEZ0UjJXV0ZaUUVwa3pGSHdJREFRQUJNQTBHQ1NxR1NJYjNEUUVCCkN3VUFBNElCQVFBSzBrM0IxNCsvVDBURkJKTDZLKzRwaGsxMHVCTTBmVmNFOWJaL2hwYmtkTUI3bTVJMEI2VUUKbUg3REcxN1NkL252bmJBdkFKUUxzayt3WHh1UDNBVTAyZFdNeUNiQXZ0Z0R0SmNOSzhuenNwb3ZpTktDQUNYSApKLy8veXNZYXI4NjdKS2NQSEFTdWpkdkpQbGVndE8xT2NhT3dmV3FNMGZWTnFGcDZ1aUtVM2lSd1JqeWgreDlXCjRTdHdXNENmZVdoWFp4U0tjd1Y0dGMvckFEQ3I3TFg4TmV4NWU5dUErMVFyTVhMTmIwTFBiYk1UdVppNklFdmwKcTRmZVJ3eGp0V1FjaDZ3Q2EzbDNWSFZrTENKVkNnNVE0cTdIRGFlYm42SzFZTVozbHRCM1RTMWdhQXNiTkZ0RgpjTC9CWmdzSHpIWWVIaUpiZjBoVW1mYUFTazNZcW1EZwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRDFVa09vektnYTR3NTYKd3FCMll6bTdubjVyTzkyZ0lpSnNkRERobkxackw0cm9kNVIxdDVjbFFleFlmZURVL2xYQWV4bnBPbEVrc21oTwpFTmhuYUdUMHRTNWUxUmVOVmllYVRLMDBxSDdyL3JPTnJoUEtYai9ZWjgzcjdWdkpzM0NuR3JBdzN2VkpySzdvCkhqTExhVEhGUk9wcWltcnRNaU5YUUZLckRubnRoeFJhc0JsSjVWT0FwM0I5cndHTDJMc3E0UWJYSkdYcjd4V3kKM0RLT2xKd1oreWhlUmJqMDNyU2grL0tmcC9VaEhjczRtbjVLS1NTYnY1aEtTdnRLN0VZNUlKVUFMcnlkVk84MgpLdVN3OTROcmZkV0xvRTBSaExNL0pNS2ZyS2Q2RzNtZXB3SXREZVZyZ1JKR2ZzR0RvYnpLTENVTThXMUhaWllWCmxBU21UTVVmQWdNQkFBRUNnZ0VBVTNITCtkckRRNElBSnRtVTR6QVZMekJXSi91UkF5c1pNbkxEUGJxa2dna0YKNHRUcDlyQ2dCTmhMb0Q0US8rSVRJUW0rWW9xbmx5Zm9Pc1dZRm5SNEFwU3VWU3QrZTJEV3o3Rk5LU0EzSytiVApCRm8xK1J2ZDg2bzdiUWlydEF3SlFZM2VhSUV1UmdVcTZXRjhQWnhtaFlkUGhUWFg4UjZnenNqZVZiankyRXZ6CnI0dDdhcHd0dS9UUm5ydlQ3UmZpUy9GNmphWHVRcThJOEUrMjAzQlhSOWhBdm1tZ2dCWjIvSUg2Vk5WZVlyZDkKVXJSblo0ejI2VmRiMFBUNFdqS0tQRnpGNUNWLzNNZzgwRXFCditlZkE2WE5GaDFva0NGMVJHbWxzbU05RkY1cgpRaXhEbFptMjJaKzdLNXgwUFYzVmdDVzR1VCtBcFJMM0UxclExeGk4UVFLQmdRRDhCYkxKWWw3VzI2ZmJOQ2swCklJMm5HbUQwd2plSnMxcEp6S2JOTUljeDJhRVpWcWFEbVpMWFQ3VXpocmZVWTBIdW5YaFpSUUZPV1RCZ0l3N0MKdE10L0JCNmpXT1ZMNGdZcCtnWWNwMi9UU1dMa3hEVzBrZlF6eDZ6VElpM0pMdEh5TkR5OXg3dms2MlNaM0h5VApWRHl1bmVRSDY0TW0zWElraFZWQlBiNDBsd0tCZ1FENU1YMmZaU29QYUdFNWQzemNQdXZvRDFxOSs3OHpmZTNxCmk4RHByQStXdHc0ZXdWQWVtVWFMNzEyWEFsZE8vM3JBeWliYURiSUhoY2lJck02eDlWSFZJMkV3V0dCUTlyOVgKTm5TWUpQdmZPY3g1VFErUThuajJkdm5Gak90VUszV2hyeVAzSEVSOTNlSGtwWFFtRkZ4WE1DWTBCTGZqYW1vdgprclE0QkhIY3VRS0JnUUN5Sm5rT29HbjRLY2ZMVFdEL0J5LzYrc3VrMlJHWFZtQXhvT2djVGZ5VGdZcSt0YUQ1CmovcmNGdTA1SWpjYWZKdWp5RTdGaytEcmVHS1k0czlSVmFvdi9FS0lKNVBYQTB4bUtlWmVKUUlJY216azE4bzYKL1oySmFOSERZZnJKcHo0am4wZDh4QThQTUZLcDdORm05L241V1lWVEQrbGk5TkQxL2dhWkdzTTB1d0tCZ1FDSApmQkVCQ00vRmNNcnJvN3VQUSthZlZUblE4WDhUVC9SN0FXRHhxMHNPZHBpR3dEUC9idmFjUHBoejhpSG1JYUZzCkVIenZNV01LRkFManpKRFUwTHlkVlk4UjZmcjBDalFlQnMxOXF4NEdVRGFML1FucGxPdVBsVUJYMkRaYW5RWm4KMGdHTDZTS1VESDgxQVlBVTlCMEFpbjA2NnhYUDM1dThJZGM2WGJCS2dRS0JnSE5CRG9HbGZMZ2VJZ1pYbFQzZwpUSEtnZ042bG9sV3k1dG9QOXlENUF3eEdxVkhLUkR2R1VLYWk2MUJnaGEyTjh3OE5pODRjVm9PTDVQWUZLRUo4CitWUTJFRXJIRGFMT3pBUlloYWZvZjAwUnF6QmpMeDZub3FwOHJuajZXZSs0T2Z6aENlYWdaT01ESlhZVVVnNnUKc0d1Tmduend4V3lEZnA2OXpSa3psOFRuCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0Kroot
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: SupervisorLocation
metadata:
  name: mobility-service-1-cluster
  namespace: mobility-service-0
spec:
  identity:
    namespace: mobility-service-0
    name: ms1-secret-tls
  host: "10.78.83.218"
  port: 6443
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: Operation
metadata:
  name: cold-migration
  namespace: mobility-service-0
spec:
  operationType: ColdMigration
  entityName: centos-cloudinit-example
  vmSpec:
    networkInterfaces:
    - networkName: "primary"
      networkType: vsphere-distributed
    className: best-effort-small
    imageName: vmi-0992e8a6bf35e6e1f
    powerState: poweredOff
  destination:
    namespace: mobility-service-0
    name: mobility-service-1-cluster
  relocateSpec:
    hostIp: "10.78.91.95"
    resourcePoolName: "mobility-service-1"
    datastoreName: "sharedVmfs-0 (1)"
    vmNetworkName: "primary-vds-2"
---
apiVersion: vmoperator.vmware.com/v1alpha1
kind: Plan
metadata:
  name: cold-migration-plan
  namespace: mobility-service-0
spec:
  operations:
    - kind: Operation
      namespace: mobility-service-0
      name: cold-migration